ktor:
    application:
        modules:
            - io.spektacle.ApplicationKt.module
    deployment:
        port: 8080
storage:
    driverClassName: "org.h2.Driver"
    jdbcURL: "jdbc:h2:files:"
    dbFilePath: build/db